# Generated by Django 3.2.16 on 2023-01-01 23:13

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_follow_проверка подписки на сомого себя'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='Проверка подписки на сомого себя'),
        ),
    ]
