# Generated by Django 3.2.16 on 2023-01-08 14:58

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow_проверка подписки на сомого себя'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Проверка подписки на сомого себя',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='Проверка подписки на самого себя'),
        ),
    ]
